import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./redux/providers";
import UnregisterSW from "./components/UnregisterSW"; // Import the new Client Component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Milk Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <UnregisterSW /> {/* Include the Client Component */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
